### ISSUE TITLE
Add React example

### ISSUE THREAD

**Issue by thiras** [capacitor-community/capacitor-googlemaps-native#63]
**Describe the solution you'd like**
It would be great if we could find a React example on the README, at least a simple one.

**Comment by aaronksaunders** [comment]
```
import {
  IonContent,
  IonHeader,
  IonPage,
  IonTitle,
  IonToolbar,
  IonLabel,
  IonItem,
  useIonViewWillEnter,
  useIonViewDidEnter,
} from "@ionic/react";
import React, { useEffect, useRef, useState } from "react";
import "./Home.css";

// capacitor built in plugins
import { Geolocation, Position } from "@capacitor/geolocation";
import { Device, DeviceInfo } from "@capacitor/device";

// community plugin
import { CapacitorGoogleMaps } from "@capacitor-community/capacitor-googlemaps-native";

const Home: React.FC = () => {
  const [location, setLocation] = useState<Position>();
  const mapRef = useRef<any>(null);

  const getLocation = async () => {
    debugger;
    let loc = await Geolocation.getCurrentPosition();
    setLocation(loc);
    return loc;
  };

  useEffect(() => {
    const initializeMaps = async () => {
      try {
        const info: DeviceInfo = await Device.getInfo();

        if (info.platform === "ios") {
          // initialize the map
          await CapacitorGoogleMaps.initialize({
            key: "YOUR_IOS_API_KEY",
          });
        }
      } catch (e) {
        console.log("Getting Device Info", e);
      }
    };

    initializeMaps();
  }, []);

  useIonViewDidEnter(async () => {
    if (!mapRef.current) return;

    const boundingRect = mapRef.current?.getBoundingClientRect() as DOMRect;

    const { coords } = await getLocation();

    CapacitorGoogleMaps.create({
      width: Math.round(boundingRect.width),
      height: Math.round(boundingRect.height),
      x: Math.round(boundingRect.x),
      y: Math.round(boundingRect.y),
      latitude: coords.latitude as number,
      longitude: coords.longitude as number,
      zoom: 12,
    });

    CapacitorGoogleMaps.addListener("onMapReady", async function () {
      /*
        We can do all the magic here when map is ready
      */

      CapacitorGoogleMaps.addMarker({
        latitude: coords.latitude as number,
        longitude: coords.longitude as number,
        title: "Custom Title",
        snippet: "Custom Snippet",
      });

      CapacitorGoogleMaps.setMapType({
        type: "normal",
      });
    });
  }, [mapRef, location]);

  return (
    <IonPage>
      <IonHeader>
        <IonToolbar>
          <IonTitle>Native Mobile</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent className="ion-padding">
        <IonLabel>Lets Use A Plugin</IonLabel>
        <IonItem>
          <IonLabel className="ion-text-wrap">
            {JSON.stringify(location, null, 2)}
          </IonLabel>
        </IonItem>
        <div id="map" ref={mapRef}></div>
      </IonContent>
    </IonPage>
  );
};

export default Home;
```

**Comment by logesh2496** [comment]
> ```
> import {
>   IonContent,
>   IonHeader,
>   IonPage,
>   IonTitle,
>   IonToolbar,
>   IonLabel,
>   IonItem,
>   useIonViewWillEnter,
>   useIonViewDidEnter,
> } from "@ionic/react";
> import React, { useEffect, useRef, useState } from "react";
> import "./Home.css";
> 
> // capacitor built in plugins
> import { Geolocation, Position } from "@capacitor/geolocation";
> import { Device, DeviceInfo } from "@capacitor/device";
> 
> // community plugin
> import { CapacitorGoogleMaps } from "@capacitor-community/capacitor-googlemaps-native";
> 
> const Home: React.FC = () => {
>   const [location, setLocation] = useState<Position>();
>   const mapRef = useRef<any>(null);
> 
>   const getLocation = async () => {
>     debugger;
>     let loc = await Geolocation.getCurrentPosition();
>     setLocation(loc);
>     return loc;
>   };
> 
>   useEffect(() => {
>     const initializeMaps = async () => {
>       try {
>         const info: DeviceInfo = await Device.getInfo();
> 
>         if (info.platform === "ios") {
>           // initialize the map
>           await CapacitorGoogleMaps.initialize({
>             key: "YOUR_IOS_API_KEY",
>           });
>         }
>       } catch (e) {
>         console.log("Getting Device Info", e);
>       }
>     };
> 
>     initializeMaps();
>   }, []);
> 
>   useIonViewDidEnter(async () => {
>     if (!mapRef.current) return;
> 
>     const boundingRect = mapRef.current?.getBoundingClientRect() as DOMRect;
> 
>     const { coords } = await getLocation();
> 
>     CapacitorGoogleMaps.create({
>       width: Math.round(boundingRect.width),
>       height: Math.round(boundingRect.height),
>       x: Math.round(boundingRect.x),
>       y: Math.round(boundingRect.y),
>       latitude: coords.latitude as number,
>       longitude: coords.longitude as number,
>       zoom: 12,
>     });
> 
>     CapacitorGoogleMaps.addListener("onMapReady", async function () {
>       /*
>         We can do all the magic here when map is ready
>       */
> 
>       CapacitorGoogleMaps.addMarker({
>         latitude: coords.latitude as number,
>         longitude: coords.longitude as number,
>         title: "Custom Title",
>         snippet: "Custom Snippet",
>       });
> 
>       CapacitorGoogleMaps.setMapType({
>         type: "normal",
>       });
>     });
>   }, [mapRef, location]);
> 
>   return (
>     <IonPage>
>       <IonHeader>
>         <IonToolbar>
>           <IonTitle>Native Mobile</IonTitle>
>         </IonToolbar>
>       </IonHeader>
>       <IonContent className="ion-padding">
>         <IonLabel>Lets Use A Plugin</IonLabel>
>         <IonItem>
>           <IonLabel className="ion-text-wrap">
>             {JSON.stringify(location, null, 2)}
>           </IonLabel>
>         </IonItem>
>         <div id="map" ref={mapRef}></div>
>       </IonContent>
>     </IonPage>
>   );
> };
> 
> export default Home;
> ```

I had done the same, but the map is not loading and getting this below error:

![image](https://user-images.githubusercontent.com/55389513/157401931-c78923e3-0e06-487b-9f44-dddf3e952553.png)

**Comment by hishivem** [comment]
Getting this error when running demo app AdvancedApp file, My project is in react ionic and i am using @transistorsoft/capacitor-background-geolocation 

index.js:245 Uncaught (in promise) Error: "BackgroundGeolocation" plugin is not implemented on web
    at createPluginMethod (index.js:245:1)
    at index.js:255:1

**Comment by hishivem** [comment]
My project is in react Ionic. Map is not visible on android app, i have added transparent css but nothing is working. Please help
